// <auto-generated />
using System;
using BootStrapECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootStrapECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BootStrapECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Elektronik",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yüksek performanslı dizüstü bilgisayar, 16GB RAM, 512GB SSD",
                            ImagePath = "/images/products/laptop.jpg",
                            IsActive = true,
                            Name = "Laptop Pro X1",
                            OldPrice = 29999.99m,
                            Price = 24999.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Elektronik",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gürültü engelleme özellikli bluetooth kulaklık",
                            ImagePath = "/images/products/headphones.jpg",
                            IsActive = true,
                            Name = "Kablosuz Kulaklık",
                            OldPrice = 1799.99m,
                            Price = 1299.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = "Elektronik",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sağlık takip özellikli akıllı saat, su geçirmez",
                            ImagePath = "/images/products/smartwatch.jpg",
                            IsActive = true,
                            Name = "Akıllı Saat",
                            Price = 3499.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB aydınlatmalı mekanik oyuncu klavyesi",
                            ImagePath = "/images/products/keyboard.jpg",
                            IsActive = true,
                            Name = "Mekanik Klavye",
                            OldPrice = 1199.99m,
                            Price = 899.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "16000 DPI hassasiyetli oyuncu faresi",
                            ImagePath = "/images/products/mouse.jpg",
                            IsActive = true,
                            Name = "Oyuncu Mouse",
                            Price = 449.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "27 inç 4K UHD IPS panel oyuncu monitörü",
                            ImagePath = "/images/products/monitor.jpg",
                            IsActive = true,
                            Name = "4K Monitör",
                            OldPrice = 10999.99m,
                            Price = 8999.99m,
                            Stock = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
